spring:
  application:
    name: math-service
  config:
    import: optional:configserver:http://localhost:8888

    
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    shutdown:
      enabled: true
#  server:
#    port: 9091
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true  