spring:
  application:
    name: math-db-service
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:mysql://localhost:3306/syne
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#
#server:
#  port: 8082
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true